/* eslint-disable prettier/prettier */
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import mongoose, { Document} from 'mongoose';
import { User } from 'src/user/model/user.schema';
import { Homework } from './homework.schema';
import { GradeComposition } from './grade-composition.schema';
export type ClassDocument = Class & Document;


// Note that the classId is for shown only
// the real id is the autoGenerated _id
@Schema()
export class Class {
 @Prop({required:true, unique:true})
 name: string
 @Prop({required: true, unique: true})
 classId: string
 @Prop({type: [{type: mongoose.Schema.Types.ObjectId, ref: 'User'}]})
 members: User[]
 @Prop({type: [{type: mongoose.Types.ObjectId, ref: 'Homework'}]})
 homeworks: Homework[]
 @Prop({unique: true})
 accessLink?: string
 @Prop({required: true, type: [{type: mongoose.Types.ObjectId, ref: 'GradeComposition'}]})
 compositions: GradeComposition[];
}

export const ClassSchema = SchemaFactory.createForClass(Class);