/* eslint-disable prettier/prettier */
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import mongoose, { Document } from 'mongoose';
export type GradeCompositionDocument = GradeComposition & Document;

// Note that the classId is for shown only
// the real id is the autoGenerated _id
@Schema()
export class GradeComposition {

  // the class _id field
  @Prop({required: true})
  classId: {type: mongoose.ObjectId, ref: 'Class'};

  @Prop({required: true, unique: true})
  name: string;

  @Prop()
  gradeScale: {type: number, min: 1, max: 100};

  @Prop()
  homeworks: {type: [mongoose.ObjectId], ref: 'Homework'};
}

export const GradeCompositionSchema = SchemaFactory.createForClass(GradeComposition);
