/* eslint-disable prettier/prettier */
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import mongoose, { Document, ObjectId } from 'mongoose';
import { User } from 'src/user/model/user.schema';

export type NotificationDocument = Notification & Document;

// Note that the classId is for shown only
// the real id is the autoGenerated _id
@Schema()
export class Notification {
  @Prop({ type: mongoose.Schema.Types.ObjectId, auto: true })
  _id: mongoose.Types.ObjectId;

  @Prop()
  name: string;

  @Prop()
  url: string;

  @Prop()
  content: string;

  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'User' })
  user: User;

  @Prop({ default: Date.now() })
  createdDate: Date;
}

export const NotificationSchema = SchemaFactory.createForClass(Notification);
